/* Narrative stages are CSS classes. Maps redraw only on resize/data load, never on scroll. */
const ownerColors={China:'#fa745e','United Arab Emirates':'#e9b46b',Singapore:'#69b6b0','Hong Kong':'#b584d8','Denmark / Netherlands':'#8ba8d4',Philippines:'#d58e67',France:'#77a7de','Switzerland / Italy':'#b2c580',Taiwan:'#dc8099','South Korea':'#a7b4d9',India:'#ddbd63',Japan:'#70bfc5'};
const origin={China:[104,35],'United Arab Emirates':[54,24],Singapore:[103.8,1.35],'Hong Kong':[114.17,22.3],'Denmark / Netherlands':[8.5,55.7],Philippines:[122,13],France:[2.2,46.2],'Switzerland / Italy':[9,46],Taiwan:[121,23],'South Korea':[128,36],India:[79,22],Japan:[138,36]};
const alias={'Viet Nam':'Vietnam',"Côte d'Ivoire":'Ivory Coast',Türkiye:'Turkey'};
const corridors=[[[120,32],[103,2],[80,7],[57,14],[44,12],[32,30],[15,38]],[[120,32],[103,2],[80,7],[55,25]], [[-80,10],[-79,9],[-77,9],[-74,10]]];
let records=[],features=[];
function name(f){return f.properties.name||f.properties.ADMIN||f.properties.NAME||''}function canonical(n){return alias[n]||n}
function hostPoint(row,path){const f=features.find(x=>canonical(name(x))===canonical(row.host));if(!f)return null;const c=path.centroid(f);return Number.isFinite(c[0])?c:null}
function arc(a,b){const mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2-Math.min(80,Math.abs(a[0]-b[0])*.13);return `M${a} Q${mx},${my} ${b}`}
function drawMap(svg,kind){const box=svg.getBoundingClientRect(),w=box.width||1200,h=box.height||700;const projection=d3.geoNaturalEarth1().fitSize([w,h],{type:'FeatureCollection',features});const path=d3.geoPath(projection);const root=d3.select(svg).attr('viewBox',`0 0 ${w} ${h}`);root.selectAll('*').remove();root.append('g').selectAll('path').data(features).join('path').attr('class','country').attr('d',path);
 const r=records.filter(d=>origin[d.owner]); const china=r.filter(d=>d.owner==='China'); const mapRows=kind==='china'?china:r; const pointRows=kind==='trade'?r.slice(0,95):mapRows;
 if(['trade','route','overlap','final'].includes(kind)){const g=root.append('g');corridors.forEach((route,i)=>g.append('path').attr('class',`route ${kind==='route'&&i===0?'active':''}`).attr('d',d3.line().curve(d3.curveBasis)(route.map(projection))));}
 if(kind==='route'){const seq=[[120,32],[103,2],[80,7],[81,7],[44,12],[32,30],[8,42]];root.append('path').attr('class','route active').attr('d',d3.line().curve(d3.curveBasis)(seq.map(projection)));seq.forEach((p,i)=>root.append('circle').attr('class','focus').attr('cx',projection(p)[0]).attr('cy',projection(p)[1]).attr('r',i===3?5:3));}
 if(kind==='china'){const g=root.append('g');china.forEach(d=>{const a=projection(origin.China),b=hostPoint(d,path);if(b)g.append('path').attr('class','connection').attr('d',arc(a,b));});}
 const dots=root.append('g'); pointRows.forEach(d=>{const p=hostPoint(d,path);if(!p)return;dots.append('circle').attr('class','port').attr('cx',p[0]).attr('cy',p[1]).attr('r',kind==='trade'?1.5:kind==='china'?3.2:2.5).attr('fill',kind==='china'?'#e9b46b':ownerColors[d.owner]||'#a7b4bc').append('title').text(`${d.port} — ${d.host}\nDataset label: ${d.owner}`)});}
function stageFor(el){const b=el.getBoundingClientRect(),travel=Math.max(el.offsetHeight-innerHeight,1);return Math.max(0,Math.min(3,Math.floor((-b.top/travel)*4)))}
function update(){document.querySelectorAll('.story').forEach(el=>{const stage=stageFor(el);for(let i=0;i<4;i++)el.classList.toggle(`stage-${i}`,i===stage)});const route=document.querySelector('#follow-route');if(route){const active=Math.min(6,Math.floor(stageFor(route)*2.2));document.querySelectorAll('.route-steps span').forEach((s,i)=>s.classList.toggle('active',i<=active));}}
async function init(){try{const [csv,world]=await Promise.all([fetch('overseas_ports.csv').then(r=>r.text()),d3.json('https://cdn.jsdelivr.net/gh/datasets/geo-countries@master/data/countries.geojson')]);records=d3.csvParse(csv).map(d=>({owner:d['Owner (Country)'].trim(),port:d['Port Name'].trim(),host:d['Hosting Country'].trim()}));const seen=new Set();records=records.filter(d=>{const k=`${d.owner}|${d.port}|${d.host}`;if(seen.has(k))return false;seen.add(k);return true});features=world.features;document.querySelectorAll('.world-map').forEach(svg=>drawMap(svg,svg.dataset.map));const key=document.querySelector('.owner-key');Object.entries(ownerColors).forEach(([n,c])=>key.insertAdjacentHTML('beforeend',`<span style="--c:${c}">${n}</span>`));}catch(e){console.warn('Map data unavailable',e)}update();}
let queued=false;addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(()=>{update();queued=false})}},{passive:true});addEventListener('resize',()=>{if(features.length)document.querySelectorAll('.world-map').forEach(svg=>drawMap(svg,svg.dataset.map));update()});init();
